import { Lexend } from "next/font/google";
import "./globals.css";
import { store } from "@/store/index";
import { StoreProvider } from "./StoreProvider";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata = {
  title: "Iniciar sesión",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='es' data-theme='light'>
      <link rel='icon' href='/favicon.ico' sizes='any' />
      <body className={lexend.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
