import { Lexend } from "next/font/google";
import "./globals.css";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata = {
  title: "Iniciar sesión",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <link rel='icon' href='/favicon.ico' sizes='any' />
      <body className={lexend.className}>{children}</body>
    </html>
  );
}
