import { Sidebar, Navbar } from "@/components";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function GeneralLayout({ children }) {
  return (
    <section className='flex bg-base-200'>
      <Sidebar />
      <div className='flex-1'>
        <Navbar />
        {children}
      </div>
    </section>
  );
}
